<template>
  <div>
    <div class="d-flex flex-column flex-sm-row justify-space-between align-sm-center mb-6">
      <div><h1 class="text-h4 font-weight-bold mb-2">Pemesanan Saya</h1><p class="grey--text mb-0">Pantau permintaan, penawaran, dan pembayaran perjalanan Anda.</p></div>
      <v-btn color="primary" large class="mt-4 mt-sm-0" to="/customer/pesan"><v-icon left>mdi-plus</v-icon>Pesan Bus</v-btn>
    </div>
    <v-skeleton-loader v-if="loading" type="list-item-three-line@3" />
    <v-alert v-else-if="error" type="error" text>{{ error }} <v-btn text small @click="loadBookings">Coba lagi</v-btn></v-alert>
    <v-card v-else-if="bookings.length" flat class="booking-list">
      <v-list><template v-for="(booking,i) in bookings">
        <v-list-item :key="booking.id" class="pa-4 pa-md-6">
          <v-list-item-avatar tile size="58" color="deep-purple lighten-5" class="rounded-lg"><v-icon color="primary">mdi-bus</v-icon></v-list-item-avatar>
          <v-list-item-content>
            <div class="d-flex flex-wrap align-center mb-1"><v-list-item-title class="font-weight-bold mr-3">{{ booking.origin }} — {{ booking.destination }}</v-list-item-title><v-chip small :color="statusInfo(booking.status).color" dark class="mr-2">{{ statusInfo(booking.status).label }}</v-chip><v-chip v-if="booking.quoted_price" small :color="paymentInfo(booking.payment_status).color" outlined>{{ paymentInfo(booking.payment_status).label }}</v-chip></div>
            <v-list-item-subtitle><v-icon x-small>mdi-calendar</v-icon> {{ formatDate(booking.departure_date) }} &nbsp; • &nbsp; {{ busName(booking.bus_type) }} &nbsp; • &nbsp; {{ booking.passenger_count }} peserta</v-list-item-subtitle>
            <div class="caption grey--text mt-1">No. {{ booking.reference_code }}</div>
            <div v-if="booking.quoted_price" class="quote mt-3 pa-3"><span>Penawaran Admin</span><strong>{{ currency(booking.quoted_price) }}</strong><small v-if="booking.admin_notes">{{ booking.admin_notes }}</small></div>
            <v-card v-if="booking.bus && booking.driver" outlined class="assignment mt-3 pa-3"><div class="font-weight-bold mb-2"><v-icon small color="primary" class="mr-1">mdi-bus-check</v-icon>Armada telah ditetapkan</div><div class="caption">Bus: <strong>{{ booking.bus.license }}</strong> · Driver: <strong>{{ booking.driver.name }}</strong></div><div v-if="booking.bus.depot" class="caption mt-1">Depo asal: {{ booking.bus.depot.name }}</div><div v-if="booking.departure_time" class="caption mt-1">Berangkat {{ booking.departure_time.slice(0,5) }} · Kembali {{ formatDate(booking.return_date) }} {{ booking.return_time.slice(0,5) }}</div></v-card>
            <v-alert v-if="booking.payment_status==='rejected'" type="error" text dense class="mt-3 mb-0">Pembayaran ditolak: {{ booking.payment_rejection_reason }}</v-alert>
            <div v-if="canPay(booking)" class="payment-actions mt-4"><v-btn color="success" @click="openPayment(booking)"><v-icon left>mdi-credit-card-outline</v-icon>{{ booking.payment_status==='rejected'?'Kirim Ulang Pembayaran':'Bayar Sekarang' }}</v-btn><v-btn v-if="canCancelRejectedPayment(booking)" color="error" outlined :loading="cancelingId===booking.id" @click="cancelRejectedPayment(booking)"><v-icon left>mdi-close-circle-outline</v-icon>Batalkan Pesanan</v-btn></div>
            <div v-if="canViewInvoice(booking)" class="payment-actions mt-4"><v-btn color="primary" outlined :loading="openingInvoiceId===booking.id" @click="viewInvoice(booking)"><v-icon left>mdi-file-document-check-outline</v-icon>Lihat Invoice</v-btn></div>
            <v-alert v-else-if="booking.quoted_price && !booking.payment_bank_name && booking.payment_status!=='paid'" type="info" text dense class="mt-3 mb-0">Menunggu Admin melengkapi rekening pembayaran.</v-alert>
          </v-list-item-content>
        </v-list-item><v-divider v-if="i<bookings.length-1" :key="`${booking.id}-divider`" />
      </template></v-list>
    </v-card>
    <v-card v-else flat class="empty pa-10 text-center"><div class="empty-icon mx-auto mb-5"><v-icon size="58" color="primary">mdi-clipboard-text-outline</v-icon></div><h2 class="text-h6 font-weight-bold">Belum ada pemesanan</h2><p class="grey--text">Mulai rencanakan perjalanan pertama Anda bersama EZBus.</p><v-btn color="primary" to="/customer/pesan">Pesan Bus Sekarang</v-btn></v-card>

    <v-dialog v-model="paymentDialog" max-width="650" persistent>
      <v-card v-if="paymentBooking"><v-card-title class="pa-5"><div><div class="text-h6 font-weight-bold">Pembayaran {{ paymentBooking.reference_code }}</div><div class="caption grey--text">Transfer sesuai nominal penawaran</div></div><v-spacer/><v-btn icon @click="paymentDialog=false"><v-icon>mdi-close</v-icon></v-btn></v-card-title><v-divider/>
        <v-card-text class="pa-6"><div class="payment-amount pa-4 text-center mb-5"><div class="caption">TOTAL PEMBAYARAN</div><div class="text-h4 font-weight-bold">{{ currency(paymentBooking.quoted_price) }}</div></div>
          <v-card outlined class="pa-4 mb-5"><div class="label">Transfer ke rekening</div><div class="text-h6 font-weight-bold">{{ paymentBooking.payment_bank_name }}</div><div class="text-h5 primary--text font-weight-bold my-1">{{ paymentBooking.payment_account_number }}</div><div>a.n. {{ paymentBooking.payment_account_holder }}</div></v-card>
          <v-alert type="warning" text dense>Pastikan nominal dan rekening sudah benar. Status lunas diberikan setelah bukti diverifikasi Admin.</v-alert>
          <v-form ref="paymentForm" v-model="paymentValid"><v-select v-model="paymentForm.method" :items="paymentMethods" outlined label="Metode transfer" :rules="required"/><v-text-field v-model.trim="paymentForm.reference" outlined label="Nomor referensi transfer" hint="Nomor transaksi dari bank atau ATM" persistent-hint :rules="required"/><v-file-input v-model="paymentForm.proof" outlined accept="image/jpeg,image/png,image/webp,application/pdf" label="Bukti pembayaran" prepend-icon="mdi-paperclip" hint="JPG, PNG, WEBP, atau PDF, maksimal 5 MB" persistent-hint :rules="proofRules" class="mt-3"/></v-form>
        </v-card-text><v-card-actions class="pa-5 pt-0"><v-spacer/><v-btn text @click="paymentDialog=false">Batal</v-btn><v-btn color="success" :loading="paying" @click="submitPayment"><v-icon left>mdi-send-check-outline</v-icon>Kirim Bukti</v-btn></v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>
<script>
export default{
 data:()=>({bookings:[],loading:false,error:null,paymentDialog:false,paymentBooking:null,paymentValid:true,paying:false,cancelingId:null,openingInvoiceId:null,paymentForm:{method:null,reference:'',proof:null},paymentMethods:[{text:'Mobile Banking',value:'mobile_banking'},{text:'Transfer ATM',value:'atm'},{text:'Transfer Bank',value:'bank_transfer'}],required:[v=>!!v||'Wajib diisi'],proofRules:[v=>!!v||'Bukti pembayaran wajib diunggah',v=>!v||v.size<=5*1024*1024||'Ukuran file maksimal 5 MB']}),
 async created(){await this.migrateLegacyBookings();await this.loadBookings()},
 methods:{
  async migrateLegacyBookings(){if(localStorage.getItem('customerBookingsMigrated')==='1')return;let legacy=[];try{legacy=JSON.parse(localStorage.getItem('customerBookings')||'[]')}catch(_){legacy=[]}if(!legacy.length){localStorage.setItem('customerBookingsMigrated','1');return}let migrated=true;for(const item of legacy){try{await axios.post('/charter-bookings',{origin:item.origin,destination:item.destination,departure_date:item.departureDate,passenger_count:item.passengers,bus_type:item.busType,notes:item.notes||null})}catch(_){migrated=false}}if(migrated){localStorage.setItem('customerBookingsMigrated','1');localStorage.removeItem('customerBookings')}},
  async loadBookings(){this.loading=true;this.error=null;try{const response=await axios.get('/charter-bookings/mine');this.bookings=response.data.bookings||[]}catch(error){this.error=error.response&&error.response.data&&error.response.data.message||'Pemesanan tidak dapat dimuat.'}finally{this.loading=false}},
  canPay(item){return Boolean(item.quoted_price&&item.payment_bank_name&&['quote_sent','approved'].includes(item.status)&&['unpaid','rejected'].includes(item.payment_status))},
  canViewInvoice(item){return item.payment_status==='paid'},
  canCancelRejectedPayment(item){return item.payment_status==='rejected'&&!['cancelled','completed'].includes(item.status)},
  openPayment(item){this.paymentBooking=item;this.paymentForm={method:null,reference:'',proof:null};this.paymentDialog=true;this.$nextTick(()=>this.$refs.paymentForm&&this.$refs.paymentForm.resetValidation())},
  async submitPayment(){if(!this.$refs.paymentForm.validate())return;this.paying=true;const data=new FormData();data.append('payment_method',this.paymentForm.method);data.append('payment_reference',this.paymentForm.reference);data.append('payment_proof',this.paymentForm.proof);try{const response=await axios.post(`/charter-bookings/${this.paymentBooking.id}/payment`,data,{headers:{'Content-Type':'multipart/form-data'}});const index=this.bookings.findIndex(item=>item.id===this.paymentBooking.id);if(index!==-1)this.$set(this.bookings,index,response.data.booking);this.paymentDialog=false;this.$notify({type:'success',title:'Pembayaran terkirim',text:response.data.message})}catch(error){const dataError=error.response&&error.response.data;const errors=dataError&&dataError.errors;this.$notify({type:'error',title:'Gagal',text:errors?Object.values(errors).reduce((a,m)=>a.concat(m),[]).join(' '):(dataError&&dataError.message)||'Bukti pembayaran gagal dikirim.'})}finally{this.paying=false}},
  async viewInvoice(item){this.openingInvoiceId=item.id;try{const response=await axios.get(`/charter-bookings/${item.id}/invoice`,{responseType:'blob'});const url=URL.createObjectURL(new Blob([response.data],{type:'text/html'}));window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){const dataError=error.response&&error.response.data;this.$notify({type:'error',title:'Gagal',text:(dataError&&dataError.message)||'Invoice tidak dapat dibuka.'})}finally{this.openingInvoiceId=null}},
  async cancelRejectedPayment(item){const result=await this.$swal.fire({title:'Batalkan pesanan?',text:`Pesanan ${item.reference_code} akan dibatalkan dan tidak diproses lebih lanjut.`,icon:'warning',showCancelButton:true,confirmButtonText:'Ya, batalkan',cancelButtonText:'Kembali'});if(!result.isConfirmed)return;this.cancelingId=item.id;try{const response=await axios.post(`/charter-bookings/${item.id}/cancel-rejected-payment`);const index=this.bookings.findIndex(booking=>booking.id===item.id);if(index!==-1)this.$set(this.bookings,index,response.data.booking);this.$notify({type:'success',title:'Pesanan dibatalkan',text:response.data.message})}catch(error){const dataError=error.response&&error.response.data;this.$notify({type:'error',title:'Gagal',text:(dataError&&dataError.message)||'Pesanan gagal dibatalkan.'})}finally{this.cancelingId=null}},
  formatDate(date){return new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T00:00:00`))},busName(type){return({medium:'Medium Bus',large:'Large Bus',luxury:'Luxury Bus'})[type]||type},currency(value){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value)},statusInfo(status){return({waiting_quote:{label:'Menunggu penawaran',color:'orange'},quote_sent:{label:'Penawaran dikirim',color:'primary'},approved:{label:'Disetujui',color:'success'},rejected:{label:'Ditolak',color:'error'},cancelled:{label:'Dibatalkan',color:'grey'},completed:{label:'Selesai',color:'teal'}})[status]||{label:status,color:'grey'}},paymentInfo(status){return({unpaid:{label:'Belum dibayar',color:'grey'},pending_verification:{label:'Menunggu verifikasi',color:'orange'},paid:{label:'Lunas',color:'success'},rejected:{label:'Pembayaran ditolak',color:'error'}})[status]||{label:status,color:'grey'}}
 }
}
</script>
<style scoped>.booking-list,.empty{border-radius:18px!important;border:1px solid #ececf3}.empty-icon{width:96px;height:96px;border-radius:50%;background:#f3edff;display:flex;align-items:center;justify-content:center}.quote{display:flex;flex-direction:column;max-width:360px;border-radius:10px;background:#f4efff;color:#6f36d8}.quote strong{font-size:1.15rem}.quote small{color:#716b7c;margin-top:4px}.payment-actions{display:flex;flex-wrap:wrap;gap:12px}.payment-amount{border-radius:14px;background:#f2eaff;color:#6f36d8}.label{font-size:.75rem;color:#8a8494;text-transform:uppercase;letter-spacing:.04em}</style>
