<template>
  <div class="booking-page">
    <div class="mb-6"><h1 class="text-h4 font-weight-bold mb-2">Pesan Bus Pariwisata</h1><p class="grey--text">Ceritakan rencana perjalanan Anda. Tim kami akan menyiapkan penawaran terbaik.</p></div>
    <v-stepper v-model="step" alt-labels class="booking-stepper" flat>
      <v-stepper-header><template v-for="(label,i) in labels"><v-stepper-step :key="`s${i}`" :complete="step > i+1" :step="i+1">{{ label }}</v-stepper-step><v-divider v-if="i<labels.length-1" :key="`d${i}`" /></template></v-stepper-header>
      <v-stepper-items>
        <v-stepper-content step="1"><v-form ref="tripForm" v-model="validTrip"><h2 class="text-h6 font-weight-bold mb-5">Detail perjalanan</h2><v-row><v-col cols="12" md="6"><v-text-field v-model="form.origin" outlined label="Lokasi penjemputan" prepend-inner-icon="mdi-map-marker" :rules="required" /></v-col><v-col cols="12" md="6"><v-text-field v-model="form.destination" outlined label="Kota atau lokasi tujuan" prepend-inner-icon="mdi-map-marker-check" :rules="required" /></v-col><v-col cols="12" md="6"><v-menu v-model="dateMenu" :close-on-content-click="false" offset-y min-width="auto"><template #activator="{on,attrs}"><v-text-field v-model="form.departureDate" outlined readonly label="Tanggal berangkat" prepend-inner-icon="mdi-calendar" v-bind="attrs" v-on="on" :rules="required" /></template><v-date-picker v-model="form.departureDate" :min="today" @input="dateMenu=false" /></v-menu></v-col><v-col cols="12" md="6"><v-text-field v-model.number="form.passengers" outlined type="number" min="1" label="Jumlah peserta" prepend-inner-icon="mdi-account-group" :rules="passengerRules" /></v-col><v-col cols="12"><v-textarea v-model="form.notes" outlined rows="3" label="Catatan perjalanan (opsional)" placeholder="Contoh: study tour sekolah, menginap 2 malam, membutuhkan bagasi besar" /></v-col></v-row></v-form></v-stepper-content>
        <v-stepper-content step="2"><h2 class="text-h6 font-weight-bold mb-2">Pilih jenis bus</h2><p class="grey--text mb-5">Anda dapat memilih kelas yang diinginkan. Ketersediaan armada akan dikonfirmasi admin.</p><v-row><v-col v-for="bus in buses" :key="bus.value" cols="12" md="4"><v-card flat :class="['choice-card pa-0 overflow-hidden',{'selected':form.busType===bus.value}]" @click="form.busType=bus.value"><div class="choice-visual"><v-img :src="bus.image" :alt="bus.title" height="150" gradient="to bottom, rgba(0,0,0,.04), rgba(0,0,0,.32)" /><v-icon class="choice-check" :color="form.busType===bus.value?'white':'rgba(255,255,255,.86)'">{{ form.busType===bus.value?'mdi-check-circle':'mdi-circle-outline' }}</v-icon></div><div class="pa-5"><h3 class="text-h6 font-weight-bold">{{ bus.title }}</h3><div class="primary--text body-2 mb-2">{{ bus.capacity }}</div><p class="grey--text body-2 mb-0">{{ bus.text }}</p></div></v-card></v-col></v-row></v-stepper-content>
        <v-stepper-content step="3"><h2 class="text-h6 font-weight-bold mb-5">Periksa kembali pemesanan</h2><v-card flat class="summary pa-5"><v-row><v-col cols="12" md="6"><div class="summary-label">Rute perjalanan</div><div class="font-weight-bold">{{ form.origin }} <v-icon small>mdi-arrow-right</v-icon> {{ form.destination }}</div></v-col><v-col cols="6" md="3"><div class="summary-label">Tanggal</div><div class="font-weight-bold">{{ formattedDate }}</div></v-col><v-col cols="6" md="3"><div class="summary-label">Peserta</div><div class="font-weight-bold">{{ form.passengers }} orang</div></v-col><v-col cols="12" md="6"><div class="summary-label">Jenis bus</div><div class="font-weight-bold">{{ selectedBus.title }}</div></v-col><v-col cols="12" md="6"><div class="summary-label">Catatan</div><div>{{ form.notes || '-' }}</div></v-col></v-row></v-card><v-alert type="info" text class="mt-5">Pengiriman formulir ini belum merupakan pembayaran. Admin akan mengirim penawaran harga setelah memeriksa armada.</v-alert></v-stepper-content>
      </v-stepper-items>
      <div class="d-flex justify-space-between pa-5 pt-0"><v-btn v-if="step>1" text @click="step--"><v-icon left>mdi-arrow-left</v-icon>Kembali</v-btn><v-spacer/><v-btn color="primary" large :loading="submitting" @click="next">{{ step===3?'Kirim Permintaan':'Lanjut' }}<v-icon right>{{ step===3?'mdi-send':'mdi-arrow-right' }}</v-icon></v-btn></div>
    </v-stepper>
    <v-snackbar v-model="saved" color="success" timeout="3500">Permintaan booking berhasil disimpan.<template #action="{attrs}"><v-btn text v-bind="attrs" to="/customer/pemesanan">Lihat</v-btn></template></v-snackbar>
  </div>
</template>
<script>
export default {
 data:()=>({step:1,labels:['Perjalanan','Pilih Bus','Konfirmasi'],validTrip:false,dateMenu:false,saved:false,submitting:false,today:new Date().toISOString().slice(0,10),required:[v=>!!v||'Wajib diisi'],passengerRules:[v=>!!v||'Wajib diisi',v=>Number(v)>0||'Minimal 1 peserta'],form:{origin:'',destination:'',departureDate:'',passengers:null,notes:'',busType:''},buses:[{value:'medium',title:'Medium Bus',capacity:'25-35 kursi',image:'https://images.pexels.com/photos/19517915/pexels-photo-19517915.jpeg?auto=compress&cs=tinysrgb&w=900',text:'Cocok untuk rombongan sedang.'},{value:'large',title:'Large Bus',capacity:'45-59 kursi',image:'https://images.pexels.com/photos/18029643/pexels-photo-18029643.jpeg?auto=compress&cs=tinysrgb&w=900',text:'Pilihan utama untuk study tour.'},{value:'luxury',title:'Luxury Bus',capacity:'18-32 kursi',image:'https://images.pexels.com/photos/29702987/pexels-photo-29702987.jpeg?auto=compress&cs=tinysrgb&w=900',text:'Fasilitas premium dan lebih lega.'}]}),
 computed:{selectedBus(){return this.buses.find(b=>b.value===this.form.busType)||{}},formattedDate(){if(!this.form.departureDate)return '-';return new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${this.form.departureDate}T00:00:00`))}},
 methods:{async next(){if(this.step===1){if(!this.$refs.tripForm.validate())return;this.step=2;return}if(this.step===2){if(!this.form.busType){this.$notify({type:'warning',title:'Pilih jenis bus terlebih dahulu'});return}this.step=3;return}this.submitting=true;try{const response=await axios.post('/charter-bookings',{origin:this.form.origin,destination:this.form.destination,departure_date:this.form.departureDate,passenger_count:this.form.passengers,bus_type:this.form.busType,notes:this.form.notes||null});this.saved=true;this.$notify({type:'success',title:'Booking terkirim',text:response.data.message});setTimeout(()=>this.$router.push('/customer/pemesanan'),700)}catch(error){const data=error.response&&error.response.data;const errors=data&&data.errors;const message=errors?Object.values(errors).reduce((all,messages)=>all.concat(messages),[]).join(' '):(data&&data.message)||'Permintaan booking gagal dikirim.';this.$notify({type:'error',title:'Gagal',text:message})}finally{this.submitting=false}}}
}
</script>
<style scoped>.booking-page{max-width:1050px;margin:auto}.booking-stepper{border-radius:20px!important;border:1px solid #ececf3}.choice-card{height:100%;border:2px solid #ececf3;border-radius:16px!important;cursor:pointer;transition:.2s}.choice-card:hover,.choice-card.selected{border-color:#8b4df0;background:#faf7ff}.choice-visual{position:relative;height:150px}.choice-check{position:absolute;right:14px;top:12px;text-shadow:0 2px 10px rgba(0,0,0,.35)}.summary{background:#f8f7fb;border-radius:15px!important}.summary-label{font-size:.78rem;color:#8a8494;margin-bottom:5px;text-transform:uppercase;letter-spacing:.04em}</style>
